# create /kangxh.com in the same folder of dockerfile.
# copy necessary code into kangxh.com folder. it will be used to build the image.

FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN pip install --upgrade pip

ADD / /app
